### ISSUE TITLE
The provided CSRF token is not valid

### ISSUE THREAD

**Issue by MelvinAchterhuis** [buckaroo-it/Shopware6#31]
After updating to 1.3.0 the following error occurs when adding an line item to the cart

`[2022-03-01T08:44:38.451352+00:00] request.ERROR: Uncaught PHP Exception Shopware\Storefront\Framework\Csrf\Exception\InvalidCsrfTokenException: "The provided CSRF token is not valid" at /Users/melvinachterhuis/sites/customer/vendor/shopware/storefront/Framework/Csrf/CsrfRouteListener.php line 117 {"exception":"[object] (Shopware\\Storefront\\Framework\\Csrf\\Exception\\InvalidCsrfTokenException(code: 0): The provided CSRF token is not valid at /Users/melvinachterhuis/sites/customer/vendor/shopware/storefront/Framework/Csrf/CsrfRouteListener.php:117)"} []`

When disabling the Buckaroo plugin the error is gone and adding items to the cart works as expected.

**Comment by Buckaroo-Rens** [comment]
Hello @MelvinAchterhuis we will look into this a.s.a.p. keep you posted.

**Comment by Buckaroo-Rens** [comment]
@MelvinAchterhuis Can you e-mail me at r.gerritsen@buckaroo.nl we are unable to reproduce it so any access to a staging environment would be helpful here.

**Comment by nielsVoogt** [comment]
@MelvinAchterhuis Did you manage to find a solution?
I'm also encountering this problem locally when running dockware on 6.4.6.0 and buckaroo 1.3.0

**Comment by nielsVoogt** [comment]
@Buckaroo-Rens  
I was also experiencing this issue (local only), so I did a little research on what could be the problem here.
First thing I tried was clean install of different shopware- and Buckaroo versions, problem persisted as @MelvinAchterhuis describes. Then I tried it in Firefox and the plugin worked as expected, I could add to my shoppingbasket without the CSRF error.

But it did show a warning in my console:

`
Cookie “session-” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute,
`

Since [1.3.0](https://github.com/buckaroo-it/Shopware_6/commit/10396ad08fdda7d2c7d1fdf37fd3d719a0b69cc0) there's a `framework.yaml` file that sets `cookie_samesite: none`. Firefox still accepts setting these cookies, but Chrome already rejects setting these because they miss the secure attribute.

Adding the folowing file in the root html directory of shopware is what fixed the problem for me.

src/config/packages/framework.yaml

```
framework:
    session:
        cookie_secure: true
```

Cookies, PHP and symfony configuration files are not really my cup of tea t.b.h. but maybe this helps somebody in the future to make a PR or solve it for themselves locally.
